[package]
name = "bevy_denshi_ika_camera_spring_arm"
edition = "2021"
version = "0.1.0"

[dependencies]
bevy = { workspace = true }
bevy_denshi_ika_gen_plugin = { workspace = true }
bevy_xpbd_3d = { workspace = true }
